# Exercícios em Python 8: Numpy



## Preparando o ambiente

Este notebook usa códigos no pacote ceai_python_aula08.py.
Execute o código a seguir.

In [ ]:
!git clone https://gitlab.uspdigital.usp.br/thiago/curso_ai_python.git
import sys
sys.path.append('curso_ai_python')

Se o bloco acima foi executado corretamente, importe os símbolos com a linha seguinte:

In [ ]:
import ceai_python_aula08

## 8.1 O objeto ```numpy.array```

O objeto ```numpy.array``` é o objeto central da biblioteca numpy.
Ele descreve um agregado multi-dimensional de dados.


Há diversas formas de se criar um objeto ```numpy.array```.
A maneira mais simples é a partir de dados agregados básicos de Python, como listas e sequências.

Exemplo: Este código cria uma matriz identidade 2x2:

In [ ]:
import numpy
numpy.array([[1,0],[0,1]])

array([[1, 0],
       [0, 1]])

Exemplo: Este código cria um vetor com 3 posições:

In [ ]:
numpy.array([1,2,3])

array([1, 2, 3])

### Exercício 8.1.1:

Crie um objeto ```numpy.array``` com uma matriz com duas linhas e 3 colunas.
Em cada componente deve estar a *soma* de 3x o valor índice da linha com o valor do índice da coluna (note que os índices são baseados em zero). Coloque o seu resultado na variável ```matriz```


In [ ]:
matriz = # Complete com seu código

Teste o seu código:

In [ ]:
ceai_python_aula08.valida_ex_08_01_01(matriz)

Objetos podem também ser criados a partir de valores *constantes*
Por exemplo, o código abaixo cria um vetor de 6 posições com zeros:

In [ ]:
numpy.zeros(6)

array([0., 0., 0., 0., 0., 0.])

#### Exercício 8.1.2:

Crie uma matriz com 20 linhas e 50 colunas, todas com zeros. Coloque o seu resultado na variável ```matriz```


In [ ]:
matriz = # complete com seu código

Teste sua resposta:

In [ ]:
ceai_python_aula08.valida_ex_08_01_02(matriz)

Pode-se criar um vetor com uma partição regular de um intervalo.
Por exemplo, o código a seguir inicializa um vetor com os números de 0 a 9,5 de 0,5 em 0,5:

In [ ]:
numpy.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

#### Exercício 8.1.3:

Crie um vetor com os valores de 0 a 100 (não-incluso) de 0,1 em 0,1. Coloque seu resultado na variável ```vetor```.

In [ ]:
vetor = # complete com seu código

Teste sua resposta:

In [ ]:
ceai_python_aula08.valida_ex_08_01_03(vetor)

## 8.2 Aplicando funções a objetos

A biblioteca numpy permite aplicar operações aritméticas e funções coeficiente-a-coecifiente a objetos.

Por exemplo, este código gera um vetor com os números de 0 a 9,9 de 0.1 a 0.1 e depois calcula a raiz quadrada destes números.

In [ ]:
numpy.sqrt(numpy.arange(0,10,0.1))

array([0.        , 0.31622777, 0.4472136 , 0.54772256, 0.63245553,
       0.70710678, 0.77459667, 0.83666003, 0.89442719, 0.9486833 ,
       1.        , 1.04880885, 1.09544512, 1.14017543, 1.18321596,
       1.22474487, 1.26491106, 1.30384048, 1.34164079, 1.37840488,
       1.41421356, 1.44913767, 1.4832397 , 1.51657509, 1.54919334,
       1.58113883, 1.61245155, 1.64316767, 1.67332005, 1.70293864,
       1.73205081, 1.76068169, 1.78885438, 1.81659021, 1.84390889,
       1.87082869, 1.8973666 , 1.92353841, 1.94935887, 1.97484177,
       2.        , 2.02484567, 2.04939015, 2.07364414, 2.0976177 ,
       2.12132034, 2.14476106, 2.16794834, 2.19089023, 2.21359436,
       2.23606798, 2.25831796, 2.28035085, 2.30217289, 2.32379001,
       2.34520788, 2.36643191, 2.38746728, 2.40831892, 2.42899156,
       2.44948974, 2.46981781, 2.48997992, 2.50998008, 2.52982213,
       2.54950976, 2.56904652, 2.58843582, 2.60768096, 2.62678511,
       2.64575131, 2.66458252, 2.68328157, 2.70185122, 2.72029

### Exercício 8.2.1:

Inicialize um vetor com os valores de 0 a 2π (```2*numpy.pi```) separados por 0,005.
Crie um outro vetor com os valores do seno (```numpy.sin```) de cada um dos componentes. Atribua o seu resultado à variável ```vetor_seno```.

Faça o mesmo com a função cosseno (```numpy.cos```) e atribua o resultado à variável ```vetor_coseno```.

In [ ]:
vetor_seno = # complete com seu código

In [ ]:
vetor_coseno = # complete com seu código

Teste o seu resultado:

In [ ]:
ceai_python_aula08.valida_ex_08_02_01(vetor_seno, vetor_coseno)

## 8.3 Operações de redução:

A biblioteca numpy permite calcular resultados totais sobre um determinado objeto.

Exemplo:
O código a seguir calcula a soma dos números de 0 a 100:

In [ ]:
numpy.arange(0,101,1).sum()

5050

### Exercício 8.3.1:

Usando os vetores ```vetor_seno``` e ```vetor_coseno``` do item anterior, mostre numericamente a "ortogonalidade" das funções.
Calcule o vetor produto coeficiente-a-coeficiente dos dois vetores e em seguida o seu total:

O valor absoluto do resultado deve ser inferior a 0,001